import type { AnySection, HomeIcon, StrapiMedia } from "./shared";
import { toFeatureImage, toIcon } from "./shared";

export type StrapiFeature = {
  id: number;
  title: string;
  subtitle: string | null;
  icon: StrapiMedia | null;
  image: StrapiMedia[];
};

export type StrapiComparisonItem = { id: number; label: string; valueLabel: string; barPercent: number };

export type StrapiComparisonBanner = {
  id: number;
  title: string;
  subtitle: string;
  comparision: StrapiComparisonItem[];
};

export type StrapiValuePropositionSection = {
  id: number;
  title: string;
  subtitle: string;
  highlightTitle: string;
  features: StrapiFeature[];
  comparisonBanner: StrapiComparisonBanner;
  __component: "home.value-proposition";
};

export type Differentiator = { id: string; title: string; description: string; icon: HomeIcon | null; image: HomeIcon | null };

export type ComparisonMetric = { label: string; displayValue: string; barPercent: number };

export type ValuePropositionData = {
  title: string;
  highlightTitle: string;
  subtitle: string;
  differentiators: Differentiator[];
  comparisonBanner: { title: string; subtitle: string; metrics: ComparisonMetric[] };
};

export function pickValuePropositionSection(sections: AnySection[]): StrapiValuePropositionSection | undefined {
  return sections.find((s): s is StrapiValuePropositionSection => s.__component === "home.value-proposition");
}

export const DEFAULT_VALUE_PROPOSITION_DATA: ValuePropositionData = {
  title: "Don't Migrate. Re-Imagine.",
  highlightTitle: "Re-Imagine.",
  subtitle:
    "Lifting and shifting legacy code is a path to obsolescence. The AI era demands a clean slate, orchestrated by intelligent agents that build natively for modern scale.",
  differentiators: [
    {
      id: "copilot-to-agentic",
      title: "From Copilot to Agentic",
      description:
        "We don't just use AI to suggest code; we deploy agents to own entire domains of the software lifecycle, from build to test to deploy.",
      icon: null,
      image: { url: "/samples/dm-copilot.png", alt: "From Copilot to Agentic" },
    },
    {
      id: "eradicate-tech-debt",
      title: "Eradicate Technical Debt",
      description: "Code generated by OrbitAI™ is uniformly structured, fully documented, and instantly refactorable across teams.",
      icon: null,
      image: { url: "/samples/dm-tech-debt.png", alt: "Eradicate Technical Debt" },
    },
    {
      id: "infinite-scalability",
      title: "Infinite Scalability",
      description: "Architecture that adapts and scales automatically based on predictive AI models, handling any load without manual intervention.",
      icon: null,
      image: { url: "/samples/dm-scalability.png", alt: "Infinite Scalability" },
    },
  ],
  comparisonBanner: {
    title: "Why AI-First Matters",
    subtitle: "We don't “add” AI to our process; we built our process around the capabilities of LLMs and autonomous agents.",
    metrics: [
      { label: "Traditional Development", displayValue: "Months", barPercent: 88 },
      { label: "OrbitAI™ Delivery", displayValue: "6 Weeks", barPercent: 26 },
    ],
  },
};

export function toValueProposition(section: StrapiValuePropositionSection): ValuePropositionData {
  const differentiators: Differentiator[] = section.features.map((feature) => ({
    id: String(feature.id),
    title: feature.title,
    description: feature.subtitle ?? "",
    icon: toIcon(feature.icon),
    image: toFeatureImage(feature.image),
  }));

  const metrics: ComparisonMetric[] = section.comparisonBanner.comparision.map((item) => ({
    label: item.label,
    displayValue: item.valueLabel,
    barPercent: item.barPercent,
  }));

  return {
    title: section.title,
    highlightTitle: section.highlightTitle,
    subtitle: section.subtitle,
    differentiators: differentiators.length > 0 ? differentiators : DEFAULT_VALUE_PROPOSITION_DATA.differentiators,
    comparisonBanner: {
      title: section.comparisonBanner.title,
      subtitle: section.comparisonBanner.subtitle,
      metrics: metrics.length > 0 ? metrics : DEFAULT_VALUE_PROPOSITION_DATA.comparisonBanner.metrics,
    },
  };
}
